<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="text" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="language" type="xs:integer" use="optional"/>
            <xs:attribute name="name" type="xs:string" use="optional"/>
            <xs:attribute name="description" type="xs:string" use="optional"/>
            <xs:attribute name="author" type="xs:string" use="optional"/>
            <xs:attribute name="date" type="xs:string" use="optional"/>
            <xs:attribute name="save" type="xs:boolean" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="dependency" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:string" use="optional"/>
            <xs:attribute name="name" type="xs:string" use="optional"/>
            <xs:attribute name="optional" type="xs:boolean" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="description" type="xs:string" use="optional"/>
      <xs:attribute name="author" type="xs:string" use="optional"/>
      <xs:attribute name="version" type="xs:string" use="optional"/>
      <xs:attribute name="date" type="xs:string" use="optional"/>
      <xs:attribute name="save" type="xs:boolean" use="optional"/>
      <xs:attribute name="sync" type="xs:boolean" use="optional"/>
      <xs:attribute name="enabled" type="xs:boolean" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
